/** Map ISO 2-letter country codes to full country names
 * Used because Nationalize API only returns country_id (e.g., "NG")
 * but your DB requires country_name (e.g., "Nigeria")
 */

export const countryMap = {
  // AFRICA
  NG: "Nigeria",
  GH: "Ghana",
  KE: "Kenya",
  UG: "Uganda",
  TZ: "Tanzania",
  ZA: "South Africa",
  CM: "Cameroon",
  EG: "Egypt",
  ET: "Ethiopia",
  SD: "Sudan",
  DZ: "Algeria",
  MA: "Morocco",
  SN: "Senegal",
  CI: "Ivory Coast",
  ML: "Mali",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  AO: "Angola",
  CG: "Republic of the Congo",
  CD: "Democratic Republic of the Congo",
  RW: "Rwanda",
  BI: "Burundi",
  MW: "Malawi",
  MZ: "Mozambique",
  NA: "Namibia",
  BW: "Botswana",
  LS: "Lesotho",
  GM: "Gambia",
  LR: "Liberia",
  SL: "Sierra Leone",
  TG: "Togo",
  BJ: "Benin",
  NE: "Niger",
  TD: "Chad",
  CF: "Central African Republic",
  ER: "Eritrea",
  DJ: "Djibouti",
  SO: "Somalia",
  GQ: "Equatorial Guinea",
  GA: "Gabon",
  CV: "Cape Verde",
  SC: "Seychelles",
  MU: "Mauritius",
  MG: "Madagascar",

  // EUROPE
  GB: "United Kingdom",
  FR: "France",
  DE: "Germany",
  IT: "Italy",
  ES: "Spain",
  NL: "Netherlands",
  BE: "Belgium",
  SE: "Sweden",
  NO: "Norway",
  DK: "Denmark",
  FI: "Finland",
  PL: "Poland",
  CH: "Switzerland",
  AT: "Austria",
  IE: "Ireland",
  PT: "Portugal",
  GR: "Greece",
  CZ: "Czech Republic",
  HU: "Hungary",
  RO: "Romania",
  BG: "Bulgaria",
  UA: "Ukraine",
  RU: "Russia",

  // NORTH AMERICA
  US: "United States",
  CA: "Canada",
  MX: "Mexico",

  // SOUTH AMERICA
  BR: "Brazil",
  AR: "Argentina",
  CO: "Colombia",
  CL: "Chile",
  PE: "Peru",
  VE: "Venezuela",
  EC: "Ecuador",
  BO: "Bolivia",
  PY: "Paraguay",
  UY: "Uruguay",

  // ASIA
  CN: "China",
  IN: "India",
  JP: "Japan",
  KR: "South Korea",
  KP: "North Korea",
  SG: "Singapore",
  MY: "Malaysia",
  ID: "Indonesia",
  TH: "Thailand",
  VN: "Vietnam",
  PH: "Philippines",
  BD: "Bangladesh",
  PK: "Pakistan",
  LK: "Sri Lanka",
  AE: "United Arab Emirates",
  SA: "Saudi Arabia",
  QA: "Qatar",
  KW: "Kuwait",
  OM: "Oman",
  IR: "Iran",
  IQ: "Iraq",
  IL: "Israel",
  TR: "Turkey",

  // OCEANIA
  AU: "Australia",
  NZ: "New Zealand",
  PG: "Papua New Guinea",
  FJ: "Fiji"
};